### ISSUE TITLE
Update to https

### ISSUE THREAD

**Issue by oisteink** [rattletone/lastfm-node-client#5]
Can you update this to https and republish npm?
auth.getMobileSession complains that it needs it: https://www.last.fm/api/show/auth.getMobileSession

**Comment by rattletone** [comment]
I've patched this in the latest release, [2.2.0](https://github.com/rattletone/lastfm-node-client/releases/tag/v2.2.0).

**Comment by oisteink** [comment]
Thanks!

lør. 14. mar. 2020 kl. 19:10 skrev Samuel Taylor <notifications@github.com>:
